FROM openjdk:17-alpine

WORKDIR /app

# Copy only the necessary files for building and testing
COPY build.gradle .
COPY settings.gradle .
COPY gradlew .
COPY gradlew.bat .
COPY gradle gradle
COPY src src
COPY src/main/resources/yml/application-test.yml application.yml

# Keep container running
CMD tail -f /dev/null