FROM openjdk:17-alpine

WORKDIR /app

# Copy only the necessary files for building and testing
COPY build.gradle .
COPY settings.gradle .
COPY gradlew .
COPY gradlew.bat .
COPY gradle gradle
COPY src src

RUN ./gradlew build -x test

# Copy the test resources
COPY build/resources/main/yml/application-test.yml application.yml

# Run the tests
# CMD ["./gradlew", "test"]