spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
        
# logging:
#   level:
#     org.hibernate.SQL: DEBUG
#     org.hibernate.type: TRACE


jwt:
  expiration: 3600000
  secret: w7bGvSDpvsKvwqfCtsOpwrHCg8OtwrDCgsKTw6TDq8O7wrjCtsOsw7/Dq8Kxw7fDqMO9

aws:
  access-key: test
  secret-key: test
  region: test
  s3-bucket: test
        
