spring:
  profiles:
    active: test

  datasource:
    url: jdbc:postgresql://db:5432/imjang-test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3-bucket: ${AWS_S3_BUCKET}
