#name: Docker Build and Test
#
#on:
#  push:
#    branches:
#      - "*"
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  build-and-test:
#    runs-on: ubuntu-latest
#    env:
#      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
#      JWT_SECRET: ${{ secrets.JWT_SECRET }}
#      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
#      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
#      AWS_REGION: ${{ secrets.AWS_REGION }}
#      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#      DOCKER_COMPOSE_CMD: docker-compose -f docker-compose.test.yml
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Build and run Docker container
#        run: $DOCKER_COMPOSE_CMD up -d --build --force-recreate
#
#      - name: Wait for container to start
#        run: sleep 5
#
#      - name: Run tests
#        run: $DOCKER_COMPOSE_CMD exec -T app ./gradlew test
#
#      - name: Stop and remove container
#        run: $DOCKER_COMPOSE_CMD down