name: Docker Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run Docker container
        run: docker-compose up -d --build --force-recreate

      - name: Wait for container to start
        run: sleep 5

      - name: Run tests
        run: docker-compose exec -T app ./gradlew test

      - name: Stop and remove container
        run: docker-compose down
